# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  jasm8080_config = debug

else ifeq ($(config),release)
  jasm8080_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := jasm8080

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

jasm8080:
ifneq (,$(jasm8080_config))
	@echo "==== Building jasm8080 ($(jasm8080_config)) ===="
	@${MAKE} --no-print-directory -C . -f jasm8080.make config=$(jasm8080_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f jasm8080.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   jasm8080"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"